### ISSUE TITLE
Gem fails to build on Ruby 2.0, ID_ALLOCATOR undeclared

### ISSUE THREAD

**Issue by agrimm** [ruby-prof/ruby-prof#91]
Ruby-prof fails to build on Ruby 2.0 . It seems to work ok with earlier versions of Ruby.

```
Andrew-Grimms-MacBook-Pro:ruby-prof agrimm$ ruby --version
ruby 2.0.0dev (2012-10-12 trunk 37163) [x86_64-darwin10.8.0]
Andrew-Grimms-MacBook-Pro:ruby-prof agrimm$ gem install pkg/ruby-prof-0.11.2.gem 
Building native extensions.  This could take a while...
ERROR:  Error installing pkg/ruby-prof-0.11.2.gem:
    ERROR: Failed to build gem native extension.

        /Users/agrimm/.rvm/rubies/ruby-head/bin/ruby extconf.rb
checking for sys/times.h... yes
checking for rb_os_allocated_objects()... no
checking for rb_gc_allocated_size()... no
checking for rb_gc_collections()... no
checking for rb_gc_time()... no
checking for rb_class_superclass()... yes
checking for rb_heap_total_mem()... no
checking for rb_gc_heap_info()... no
creating Makefile

make
compiling rp_call_info.c
compiling rp_measure.c
compiling rp_measure_allocations.c
compiling rp_measure_cpu_time.c
compiling rp_measure_gc_runs.c
compiling rp_measure_gc_time.c
compiling rp_measure_memory.c
compiling rp_measure_process_time.c
compiling rp_measure_wall_time.c
compiling rp_method.c
rp_method.c: In function ‘method_name’:
rp_method.c:101: error: ‘ID_ALLOCATOR’ undeclared (first use in this function)
rp_method.c:101: error: (Each undeclared identifier is reported only once
rp_method.c:101: error: for each function it appears in.)
make: *** [rp_method.o] Error 1


Gem files will remain installed in /Users/agrimm/.rvm/gems/ruby-head/gems/ruby-prof-0.11.2 for inspection.
Results logged to /Users/agrimm/.rvm/gems/ruby-head/gems/ruby-prof-0.11.2/ext/ruby_prof/gem_make.out
Andrew-Grimms-MacBook-Pro:ruby-prof agrimm$ rvm use 1.9.3
Using /Users/agrimm/.rvm/gems/ruby-1.9.3-p194
Andrew-Grimms-MacBook-Pro:ruby-prof agrimm$ gem install pkg/ruby-prof-0.11.2.gem 
Building native extensions.  This could take a while...
Successfully installed ruby-prof-0.11.2
1 gem installed
Installing ri documentation for ruby-prof-0.11.2...
Installing RDoc documentation for ruby-prof-0.11.2...
```
